[project]
name = "relaxation-nn"
version = "0.1.0"
description = "Experiment environment for Relaxation Neural Networks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ml-collections>=1.1.0",
    "numpy>=2.4.4",
    "pinns",
    "pinns-jax",
    "pinns-utils-torch",
    "torch>=2.11.0",
    "wpinns",
]

[tool.uv.workspace]
members = ["packages/*", "libs/*"]

[tool.uv.sources]
pinns = { workspace = true }
pinns-jax = { workspace = true }
wpinns = { workspace = true }
pinns-utils-torch = { workspace = true }

[dependency-groups]
dev = ["ipython>=9.12.0", "pytest>=9.0.3"]
